package com.aliernfrog.ensicord.data

import androidx.annotation.Keep

@Keep
data class AddonJSON(
    val meta: AddonMetadataJSON
)

@Keep
data class AddonMetadataJSON(
    val name: String,
    val description: String,
    val thumbnail: String? = null,
    val authors: List<String>? = null,
    val repo: String = "unknown" // Generated by Ensicord
)
