package com.aliernfrog.ensicord.data

data class Addon(
    val name: String,
    val description: String,
    val setAppTheme: Int? = null,
    val setEnsiUserName: String? = null,
    val repo: String, //This is generated by Ensicord to save where add-on comes from
    val error: Boolean = false //This is generated by Ensicord when there's an error about the add-on
)
