package com.aliernfrog.ensicord.data

data class Addon(
    val name: String,
    val description: String,
    val thumbnailUrl: String? = null,
    val setAppTheme: String? = null,
    val setEnsiUserName: String? = null,
    val setEnsiWords: Set<String>? = null,
    val addEnsiWords: Set<String>? = null,
    val setEnsiVerbs: Set<String>? = null,
    val addEnsiVerbs: Set<String>? = null,
    var repo: String, //This is generated by Ensicord to save where add-on comes from
    val error: Boolean = false //This is generated by Ensicord when there's an error about the add-on
)
