package com.aliernfrog.ensicord.data

data class AddonJSON(
    val meta: AddonMetadataJSON
)

data class AddonMetadataJSON(
    val name: String,
    val description: String,
    val thumbnail: String? = null,
    val authors: List<String>? = null,
    val repo: String = "unknown" // Generated by Ensicord
)
