package com.aliernfrog.ensicord.data

data class Addon(
    val name: String,
    val description: String,
    val thumbnailUrl: String? = null,
    val setAppTheme: String? = null,
    val setEnsiUserName: String? = null,
    val collectionMethods: List<AddonCollectionMethod>? = null,
    var repo: String, //This is generated by Ensicord to save where add-on comes from
    val error: Boolean = false //This is generated by Ensicord when there's an error about the add-on
)